final List<Map<String, dynamic>> chats = [
  {
    "name": "FjTaylor",
    "message": "when are you going to deliver the pizza, my home?",
    "time": "11:51",
    "unread": 3,
    "avatar": "https://plus.unsplash.com/premium_photo-1689977830819-d00b3a9b7363?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YXZhdGFyc3xlbnwwfHwwfHx8MA%3D%3D",
    "isVerified" : true,
    "status" : true,
    "seen" : false,
    "sent" : false,
    "receivedByThem" : false,
    "received" : true
  },
  {
    "name": "Davisore_12",
    "message": "What are your shift hours?",
    "time": "11:51",
    "unread": 0,
    "avatar": "https://images.unsplash.com/photo-1708860028064-3303a016e88f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YXZhdGFyc3xlbnwwfHwwfHx8MA%3D%3D",
    "isVerified" : false,
    "status" : false,
    "seen" : false,
    "sent" : false,
    "receivedByThem" : false,
    "received" : true
  },
  {
    "name": "Giana@And",
    "message": "Hey, How are you!",
    "time": "11:51",
    "unread": 5,
    "avatar": "https://images.unsplash.com/photo-1711980012199-2697edfc8794?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YXZhdGFyc3xlbnwwfHwwfHx8MA%3D%3D",
    "isVerified" : true,
    "status" : true,
    "seen" : false,
    "sent" : false,
    "receivedByThem" : false,
    "received" : true
  },
  {
    "name": "Discussion Formal",
    "message": "Hope everything is going well and where are you.",
    "time": "Yesterday",
    "unread": 0,
    "avatar": "https://plus.unsplash.com/premium_photo-1689568126014-06fea9d5d341?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8YXZhdGFyc3xlbnwwfHwwfHx8MA%3D%3D",
    "isVerified" : false,
    "status" : false,
    "seen" : false,
    "sent" : false,
    "receivedByThem" : false,
    "received" : true
  },
  {
    "name": "Henery Thomas",
    "message": "What are your shift hours?",
    "time": "26/05/23",
    "unread": 0,
    "avatar": "https://images.unsplash.com/photo-1708860027560-bf3c060b26f4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YXZhdGFyc3xlbnwwfHwwfHx8MA%3D%3D",
    "isVerified" : false,
    "status" : true,
    "seen" : false,
    "sent" : true,
    "receivedByThem" : false,
    "received" : false
  },
  {
    "name": "Kyanie B.",
    "message": "Photo",
    "time": "21/03/23",
    "unread": 0,
    "avatar": "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGF2YXRhcnN8ZW58MHx8MHx8fDA%3D",
    "isVerified" : true,
    "status" : false,
    "seen" : true,
    "sent" : false,
    "receivedByThem" : false,
    "received" : false
  },
  {
    "name": "Food Factory",
    "message": "We appreciate your feedback!",
    "time": "08/01/23",
    "unread": 3,
    "avatar": "https://plus.unsplash.com/premium_photo-1689977807477-a579eda91fa2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8YXZhdGFyc3xlbnwwfHwwfHx8MA%3D%3D",
    "isVerified" : false,
    "status" : true,
    "seen" : false,
    "sent" : false,
    "receivedByThem" : false,
    "received" : true
  },
  {
    "name": "J8mesWill",
    "message": "0:08",
    "time": "23/12/22",
    "unread": 0,
    "avatar": "https://plus.unsplash.com/premium_photo-1688740375397-34605b6abe48?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGF2YXRhcnN8ZW58MHx8MHx8fDA%3D",
    "isVerified" : true,
    "status" : false,
    "seen" : false,
    "sent" : false,
    "receivedByThem" : true,
    "received" : false
  },
  {
    "name": "FlorianTales",
    "message": "New blog post: Flutter Tips!",
    "time": "21/03/23",
    "unread": 3,
    "avatar": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGF2YXRhcnN8ZW58MHx8MHx8fDA%3D",
    "isVerified" : false,
    "status" : true,
    "seen" : false,
    "sent" : false,
    "receivedByThem" : false,
    "received" : true
  },
  {
    "name": "Workplace Updates",
    "message": "Meeting rescheduled to 3 PM.",
    "time": "Today",
    "unread": 0,
    "avatar": "https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGF2YXRhcnN8ZW58MHx8MHx8fDA%3D",
    "isVerified" : false,
    "status" : true,
    "seen" : false,
    "sent" : false,
    "receivedByThem" : true,
    "received" : false
  },
  {
    "name": "Family Group",
    "message": "Don't forget the dinner at 7!",
    "time": "Yesterday",
    "unread": 4,
    "avatar": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGF2YXRhcnN8ZW58MHx8MHx8fDA%3D",
    "isVerified" : false,
    "status" : false,
    "seen" : false,
    "sent" : false,
    "receivedByThem" : false,
    "received" : true
  },
  {
    "name": "TechSupport",
    "message": "Your ticket has been resolved.",
    "time": "02/11/23",
    "unread": 0,
    "avatar": "https://images.unsplash.com/photo-1623582854588-d60de57fa33f?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "isVerified" : false,
    "status" : false,
    "seen" : true,
    "sent" : false,
    "receivedByThem" : false,
    "received" : false
  },
];